x86/tdx: Fix build issue in non TDX environment
In non TDX build, following compilation error is observed due to
missing definition of tdx_filter_init(). So add inline declaration
for it.

arch/x86/kernel/head64.c:529:2: error：implicit declaration of \
              function ‘tdx_filter_init’; did you mean \
              ‘tdx_early_init’? [-Werror=implicit-function-declaration]

Signed-off-by: Kuppuswamy Sathyanarayanan <sathyanarayanan.kuppuswamy@linux.intel.com>