fix undefined symbol of cc_init
This patch fixes the following error.

> arch/x86/kernel/cpu/mshyperv.c:349: undefined reference to `cc_init'

CONFIG_GUEST_HYPERVISOR compiles mshyperv.o that reference cc_init().
cc_init() requires CONFIG_ARCH_HAS_CC_PLATFORM.
"select ARCH_HAS_CC_PLATFORM" when CONFIG_GUEST_HYPERVISOR=y.

Fixes: cbb5c73599cf ("x86/coco: Add API to handle encryption mask")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>